- name: Install Ansible Galaxy roles
  hosts: localhost
  become: true
  tasks:
    - name: Install required roles
      ansible.builtin.command: ansible-galaxy install -r requirements.yml
    - name: Include playbook2
      include: playbook.yml